#!/usr/bin/env bash

today=$(date +%Y-%m-%d)
prev=$(git log -n 1 --format=%s)

if [[ "$today" == "$prev" ]];
then
  git add README.md; git commit --amend --no-edit
  git push --force origin master
else
  sed -i '' -e "s/TODAY/$today/" README.md
  git add README.md; git commit -m "$today"
  git push origin master
fi

